# Project language
language: php

# Allows use container-based infrastructure
sudo: false

# Start mysql service
services:
  - mysql

# Cache composer packages so "composer install" is faster
cache:
  directories:
    - $HOME/.composer/cache/files

# Define an environment variable
env:
  - SYMFONY_VERSION="4.0.*" DB=mysql

# Update composer
before-install:
  - composer self-update

# Install composer dependencies,
# Create database, schema and fixtures
install:
  - cp .env.test.dist .env
  - composer install
  - php bin/console doctrine:database:create --env=prod
  - php bin/console doctrine:schema:update --env=prod
  - php bin/console doctrine:fixtures:load -n --env=prod

# Run script
script:
  - phpunit